name: Project Automation

on:
  issues:
    types: [opened, assigned]
  pull_request:
    types: [opened, closed]

jobs:
  project-automation:
    runs-on: ubuntu-latest
    steps:
      - name: Move to In Progress
        if: github.event.action == 'assigned'
        run: |
          echo "La Issue ha sido asignada."
          echo "Aquí se ejecutaría el script para mover la card a 'In Progress'"
          
      - name: Move to Done
        if: github.event.pull_request.merged == true
        run: |
          echo "El Pull Request ha sido fusionado."
          echo "Aquí se ejecutaría el script para mover la card a 'Done'"